{
 "title": "Total Request Rate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blocked Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ratelimiter_requests_total{result=\"blocked\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Allowed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(ratelimiter_requests_total{result=\"allowed\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(ratelimiter_requests_total[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}